CREATE TABLE ITEMS (
    ID BIGINT NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    CATEGORY_ID VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(500),
    LISTED_PRICE DOUBLE NOT NULL,
    DISCOUNT DOUBLE,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (ID)
);