CREATE TABLE IF NOT EXISTS ITEMS (
    ID BIGINT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    CATEGORY_ID VARCHAR(255),
    DESCRIPTION VARCHAR(1000),
    LISTED_PRICE DOUBLE,
    DISCOUNT DOUBLE,
    QUANTITY INT
);